version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: recruitment_mysql
    environment:
      MYSQL_ROOT_PASSWORD: WellCenter2024!
      MYSQL_DATABASE: recruitment_db
      MYSQL_USER: recruitment_user
      MYSQL_PASSWORD: WellCenter2024!
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - recruitment_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pWellCenter2024!"]
      timeout: 20s
      retries: 15
      interval: 10s
      start_period: 30s

  app:
    build: .
    container_name: recruitment_app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/recruitment_db
      SPRING_DATASOURCE_USERNAME: recruitment_user
      SPRING_DATASOURCE_PASSWORD: WellCenter2024!
    networks:
      - recruitment_network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: recruitment_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - recruitment_network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  recruitment_network:
    driver: bridge
